apiVersion: apps/v1
kind: Deployment
metadata:
  name: manyu
  labels:
    app: manyu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manyu
  template:
    metadata:
      labels:
        app: manyu
    spec: 
      containers:
        - name: webapp
          image: gcr.io/alpine-realm-270806/mywebsite:v1
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "100m"
